### PR TITLE
Use correct secret name

### PR DESCRIPTION
**Pull request by BlakeASmith**

### CODE REVIEW

**Comment by igboyes** [comment]
I thought I already did this in #222.

**Comment by BlakeASmith** [comment]
> I thought I already did this in #222.

Yes you did. The change needs to be in master for the nightly build to work though since that is the version that will be used.

My initial change was not correct though. I checked out the changes you made in develop instead

**Review by igboyes — APPROVED** [review]

**Comment by igboyes** [comment]
Failing integration test is not an issue?

**Comment by BlakeASmith** [comment]
> Failing integration test is not an issue?

Here it's failing since it's running on the master branch. There's been some changes since the last release so it's expected.

**Pull request merged**
