### PR TITLE
Remove FixtureMultipleYield

### PR DESCRIPTION
**Pull request by igboyes**
* This exception is not used anywhere
* Cleaned up unused imports in `errors.py`

### CODE REVIEW

**Comment by BlakeASmith** [comment]
@igboyes  We should raise an exception in the case that a generator fixture yields more than once. I think right now that just won't be caught. 

We could also remove it and pick an applicable builtin exception. What do you think?

**Comment by igboyes** [comment]
What is a good example of a generator fixture?

**Comment by BlakeASmith** [comment]
> What is a good example of a generator fixture?

Generator fixture is any fixture with a `yield`. It is there for when there is cleanup steps to be done when the workflow instance. 

For example, a generator fixture could be used to create a temporary directory.  `work_path` is implemented in a similar way. 

```python
@fixture
def temp_path():
     tempdir = Path(...)
     tempdir.mkdir()
     yield tempdir
     shutil.rmtree(tempdir)
```

This promises that the `temp_path` will be available to the workflow and that
when the workflow completes, or fails, or is cancelled the code after the `yield` will be invoked.

**Comment by igboyes** [comment]
Yes. That is the same concept from `pytest`. I meant a built-in fixture.

You want to catch a situation like this:
```py
@fixture
def temp_path():
     tempdir = Path(...)
     tempdir.mkdir()
     yield tempdir
     yield tempdir
     shutil.rmtree(tempdir)
```
Correct?

**Comment by BlakeASmith** [comment]
> Yes. That is the same concept from `pytest`. I meant a built-in fixture.
> 
> You want to catch a situation like this:
> 
> ```python
> @fixture
> def temp_path():
>      tempdir = Path(...)
>      tempdir.mkdir()
>      yield tempdir
>      yield tempdir
>      shutil.rmtree(tempdir)
> ```
> 
> Correct?

Yes that's the situation. Right now the `shutil.rmtree` line would never run and there'd be no notification to the developer about it

**Comment by igboyes** [comment]
Issue opened: https://linear.app/virtool/issue/VIR-784/raise-exception-when-there-are-multiple-yield-statements-in-a-fixture

I'll close this PR. I think the exception should end with `Error` to follow the Python exception naming convention.

**Pull request closed without merging**
