### PR TITLE
refactor: change run_subprocess.py to subprocess.py

### PR DESCRIPTION
**Pull request by mattcurts**
based on virtool-core/logging.py, this should change it by changing the module name.

### CODE REVIEW

**Comment by mattcurts** [comment]
should I refactor the print statements like Deepsource recommends?

**Comment by mattcurts** [comment]
Since we have changed it to use the name and not the module, I guess we only need the latest commit.

**Review by igboyes — APPROVED** [review]

**Comment by igboyes** [comment]
Can you resolve the Deepsource issues on this one @mattcurts?

**Comment by igboyes** [comment]
I am going to close this because it will change again with the `structlog` switch.

**Pull request closed without merging**
